config/routes.rb
Sparta::Application.routes.draw do

  resources :projects, :except => [:show] do
    resources :project_users
    resources :ticket_statuses
    resources :ticket_types
    resources :tickets do
      collection do
        post :sort
        post :bulk_delete
        post :bulk_update
      end

      resources :comments
    end
  end

  # match "/stories/:name" => redirect {|params| "/posts/#{params[:name].pluralize}" }
  match '/projects/:id' => redirect("/projects/%{id}/tickets")

  devise_for :users

  resources :common_pages, :only => :show

  match ':id' => 'common_pages#show'
  root :to => 'common_pages#show', :id => 'home'
end

app/controllers/ticket_types_controller.rb
class TicketTypesController < InheritedResources::Base
  load_and_authorize_resource

  belongs_to :project
  actions :index, :new, :create, :edit, :update, :destroy

  def create
    create! { redirect_to :action => :index}
  end

  def update
    update! { redirect_to :action => :index}
  end
end

app/helpers/ticket_types_helper.rb
module TicketTypesHelper
end

app/views/ticket_types/_form.html.erb
<%= form_for([@project, @ticket_type]) do |f| %>
  <% if @ticket_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_type.errors.count, "error") %> prohibited this ticket_type from being saved:</h2>

      <ul>
      <% @ticket_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_types/edit.html.erb
<h1>Editing ticket_type</h1>

<%= render 'form' %>

<%= link_to 'Back', project_ticket_types_path %>

app/views/ticket_types/index.html.erb
<h1>Listing ticket_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ticket_types.each do |ticket_type| %>
  <tr>
    <td><%= ticket_type.name %></td>
    <td><%= ticket_type.color %></td>
    <td><%= link_to 'Edit', edit_project_ticket_type_path(@project, ticket_type) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket type', new_project_ticket_type_path %>

app/views/ticket_types/new.html.erb
<h1>New ticket_type</h1>

<%= render 'form' %>

<%= link_to 'Back', project_ticket_types_path %>