config/routes.rb
Sparta::Application.routes.draw do

  resources :projects, :except => [:show] do
    resources :project_users
    resources :ticket_statuses
    resources :ticket_types
    resources :tickets do
      collection do
        post :sort
        post :bulk_delete
        post :bulk_update
      end

      resources :comments
    end
  end

  # match "/stories/:name" => redirect {|params| "/posts/#{params[:name].pluralize}" }
  match '/projects/:id' => redirect("/projects/%{id}/tickets")

  devise_for :users

  resources :common_pages, :only => :show

  match ':id' => 'common_pages#show'
  root :to => 'common_pages#show', :id => 'home'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  has_many :comments, :dependent => :destroy
  belongs_to :status, :class_name => 'TicketStatus', :foreign_key => 'status_id'
  belongs_to :type, :class_name => 'TicketType', :foreign_key => 'type_id'
  belongs_to :assigned_to, :class_name => 'User', :foreign_key => 'assigned_to_id'
  belongs_to :reporter, :class_name => 'User', :foreign_key => 'reporter_id'
  
  before_create :numbering_ticket

  after_create :set_default_status
  after_create :close_if_status_closed

  after_update :close_if_status_closed

  default_scope :order => '"position" asc', :conditions => { :closed => false }

  acts_as_taggable

  #validates :description, :presence => true

  def self.order ids
    update_all(
      ['"position" = find_in_set("id"::text, ?)', ids.join(',')],
      { :id => ids }
    )
  end

private

  def numbering_ticket
    self.number = if self.project.tickets(true).size > 0
      self.project.tickets.maximum('number') + 1
    else
      1
    end
  end

  def set_default_status
    unless self.status
      self.status = project.default_status
      save
    end
  end

  def close_if_status_closed
    if !self.closed && self.status.close?
      self.closed = true
      save
    elsif self.closed && !self.status.close?
      self.closed = false
      save
    end
  end
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  belongs_to :project
  has_many :tickets, :foreign_key => 'type_id'
end

app/controllers/tickets_controller.rb
# Tickets controller
class TicketsController < InheritedResources::Base

  # Inherited resources methods

  belongs_to :project

  respond_to :js

  # Abilities

  load_and_authorize_resource :project
  load_and_authorize_resource :ticket, :through => :project

  # Index action, show list of all active tickets
  def index
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.new

    @tags = Ticket.tag_counts_on(:tags)

    if params[:tags]
      @tickets = {}
      @tickets[:both] = [params[:tags].gsub(', ', ',').split(',').map(&:capitalize).join(', '), @project.tickets.tagged_with(params[:tags])]
      @tickets[:other] = params[:tags].gsub(', ', ',').split(',').map do |tag|
        [tag.capitalize, (@project.tickets.tagged_with(tag) - @tickets[:both][1])]
      end
    else
      @tickets = @project.tickets
    end
  end

  def show
    super do |format|
      @comments = @ticket.comments
      @comment = @ticket.comments.new
      format.html do
        render :layout => false
      end
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @ticket = @project.tickets.build params[:ticket]
    @ticket.reporter_id = current_user
    create! do |format|
      format.js { render :partial => 'ticket', :locals => { :ticket => @ticket } }
    end
  end

  def update
    update! do |format|
      format.js { render :partial => 'ticket', :locals => { :ticket => @ticket } }
    end
  end

  def destroy
    destroy! do |format|
      format.js { render :nothing => true }
    end
  end

  def sort
    Ticket.order params[:ticket]
    render :nothing => true
  end

  def bulk_delete
    Ticket.delete params[:ticket]
    render :nothing => true
  end

  def bulk_update
    tickets = Ticket.update_all(params[:ticket], ["id IN (?)", params[:ticket_ids]])
    render :json => {
      :tickets => Ticket.find(params[:ticket_ids]).map { |ticket| render_to_string :partial => 'ticket', :locals => { :ticket => ticket } }
    }
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.haml
= semantic_form_for [@project, @ticket], :remote => true, :html=>{:class=>(@ticket.new_record? ? 'new' : 'edit')} do |f|
  = f.inputs do
    = f.input :description
    = f.input :tag_list
    = f.input :assigned_to, :collection => @project.users.map {|user| [user.email, user.id]}
    = f.input :status, :collection => @project.ticket_statuses.map {|status| [status.name, status.id]}
    = f.input :type, :collection => @project.ticket_types.map {|type| [type.name, type.id]}
  = f.buttons

app/views/tickets/_ticket.haml
= content_tag_for :li, ticket, :class => 'ticket' do
  %span.drag-mate= link_to image_tag('drag.gif'), '#'
  %span.number-container
    %span.number(style="background-color: #{ticket.status.color}" title="#{ticket.status.name}")= link_to "##{ticket.number}", [ticket.project, ticket]
  %span.description= ticket.description
  %span.labels
    - if ticket.type
      %span.type{:style => "background-color: #{ticket.type.color}"}= ticket.type.name
    - if ticket.assigned_to.present?
      %span.assign(class="#{current_user == ticket.assigned_to ? 'its-you' : ''}")
        = link_to ticket.assigned_to.email, '#'
  %span.buttons
    = link_to 'Edit', edit_project_ticket_path(ticket.project, ticket), :remote => true, :class => 'edit-ticket'
    = link_to image_tag('trash.gif'), [ticket.project, ticket], :class => 'delete-ticket', :confirm => 'You are really want to delete this ticket?', :method => :delete, :remote => true

app/views/tickets/edit.html.haml
%h4 Editing ticket
= render 'form'

app/views/tickets/index.html.haml
:javascript
  var projectId = #{@project.id};

%ul.tickets-actions
  %li.relative-it= link_to 'Add a new ticket'.html_safe, new_project_ticket_path, :remote => true, :class => 'button green add-ticket menu-popup menu-popup-window bright-green'

.tickets-lists

- if @tickets.class == Hash
  - if @tickets[:both]
    - unless @tickets[:both][1].empty?
      %h3.tickets-header= @tickets[:both][0]

      %ul.tickets-list
        - @tickets[:both][1].each do |ticket|
          = render ticket

  - if @tickets[:other]
    - @tickets[:other].each do |ticket|
      - unless ticket[1].empty?
        %h3.tickets-header= ticket[0]

        %ul.tickets-list
          - ticket[1].each do |t|
            = render t

- if @tickets.class == Array
  %h3.tickets-header All Tickets

  %ul.tickets-list
    - @tickets.each do |ticket|
      = render ticket

%ul#ui-sorting-helper.tickets-list

- content_for :meta_footer do
  %form{:id => 'tags_search', :method => 'get', :action => project_tickets_path}
    = label_tag 'Search'
    %input{:name => 'tags', :placeholder => 'first_tag, second_tag'}
    %input{:type => 'submit', :value => 'Show'}

  .select-tag-filter
    %form
      = label_tag 'Select tag'
      = select_tag 'tags', options_for_select(@tags.map {|t| [t.name, project_tickets_path + "?tags=#{t.name}"] } ), :class => 'select-tag'

#ticket-template
  %p Edit Tickets
  %br
  = semantic_form_for [@project, @ticket], :url => bulk_update_project_tickets_path  do |f|
    = f.inputs do
      -#= f.input :tag_list
      = f.input :assigned_to, :collection => @project.users.map {|user| [user.email, user.id]}
      = f.input :status, :collection => @project.ticket_statuses.map {|status| [status.name, status.id]}
      = f.input :type, :collection => @project.ticket_types.map {|type| [type.name, type.id]}
    = f.buttons do
      %li{:class => 'commit'}= f.submit 'Update Tickets'
  

app/views/tickets/show.html.haml
.ticket-show
  .ticket
    = link_to 'Edit', edit_project_ticket_path(@project, @ticket), :remote => true, :class => 'button edit-ticket'

    .number-and-type
      .number(style="background-color: #{@ticket.status.color}")
        %p.number ##{@ticket.number}
        %p.status= @ticket.status.name

      - if @ticket.type
        .type
          %span(style="background-color: #{@ticket.type.color}")= @ticket.type.name

    .description= @ticket.description

    .info
      %dl
        %dt Created:
        %dd= content_tag(:abbr, I18n.l(@ticket.created_at, :format => :short), :class => 'timeago', :title => @ticket.created_at.iso8601)

        - if @ticket.assigned_to.present?
          %dt Assigned to:
          %dd
            = image_tag(@ticket.assigned_to.gravatar_url.html_safe, :alt => '')
            = @ticket.assigned_to.email

        - if @ticket.reporter.present?
          %dt Reported by:
          %dd
            = image_tag(@ticket.reporter.gravatar_url.html_safe, :alt => '')
            = @ticket.reporter.email

        - if @ticket.tag_list.present?
          %dt Tags
          %dd
            - @ticket.tag_list.each do |tag|
              = link_to tag, project_tickets_path + "?tags=#{tag}"

    = render :partial => 'comments/list'