config/routes.rb
Sparta::Application.routes.draw do

  resources :projects, :except => [:show] do
    resources :project_users
    resources :ticket_statuses
    resources :ticket_types
    resources :tickets do
      collection do
        post :sort
        post :bulk_delete
        post :bulk_update
      end

      resources :comments
    end
  end

  # match "/stories/:name" => redirect {|params| "/posts/#{params[:name].pluralize}" }
  match '/projects/:id' => redirect("/projects/%{id}/tickets")

  devise_for :users

  resources :common_pages, :only => :show

  match ':id' => 'common_pages#show'
  root :to => 'common_pages#show', :id => 'home'
end

app/controllers/ticket_statuses_controller.rb
class TicketStatusesController < InheritedResources::Base

  belongs_to :project
  actions :index, :new, :create, :edit, :update, :destroy

  load_and_authorize_resource :project
  load_and_authorize_resource :ticket_status, :through => :project

  def create
    create! { redirect_to :action => :index}
  end

  def update
    update! { redirect_to :action => :index}
  end
end

app/helpers/ticket_statuses_helper.rb
module TicketStatusesHelper
end

app/views/ticket_statuses/_form.html.haml
= form_for([@project, @ticket_status]) do |f|
  - if @ticket_status.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket_status.errors.count, "error")
        prohibited this ticket_status from being saved:
      %ul
        - @ticket_status.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :color
    %br/
    = f.text_field :color
  .field
    = f.label :close
    %br/
    = f.check_box :close
  .actions
    = f.submit

app/views/ticket_statuses/edit.html.erb
<h1>Editing ticket_status</h1>

<%= render 'form' %>

<%= link_to 'Back', project_ticket_statuses_path(@project) %>

app/views/ticket_statuses/index.html.haml
%h1 Listing ticket_statuses
%table
  %tr
    %th Name
    %th Color
    %th Close
    %th
    %th
    %th
  - @ticket_statuses.each do |ticket_status|
    %tr
      %td= ticket_status.name
      %td= ticket_status.color
      %td= ticket_status.close
      %td= link_to 'Edit', edit_project_ticket_status_path(@project, ticket_status)
      %td
        -#= link_to 'Destroy', [@project, ticket_status], :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Ticket status', new_project_ticket_status_path

app/views/ticket_statuses/new.html.erb
<h1>New ticket_status</h1>

<%= render 'form' %>

<%= link_to 'Back', project_ticket_statuses_path %>