config/routes.rb
Sparta::Application.routes.draw do

  resources :projects, :except => [:show] do
    resources :project_users
    resources :ticket_statuses
    resources :ticket_types
    resources :tickets do
      collection do
        post :sort
        post :bulk_delete
        post :bulk_update
      end

      resources :comments
    end
  end

  # match "/stories/:name" => redirect {|params| "/posts/#{params[:name].pluralize}" }
  match '/projects/:id' => redirect("/projects/%{id}/tickets")

  devise_for :users

  resources :common_pages, :only => :show

  match ':id' => 'common_pages#show'
  root :to => 'common_pages#show', :id => 'home'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tickets, :dependent => :destroy
  has_many :ticket_statuses, :dependent => :destroy
  has_many :ticket_types, :dependent => :destroy

  belongs_to \
    :default_status,
    :class_name => 'TicketStatus',
    :foreign_key => 'default_status_id'

  after_create \
    :create_association_with_author,
    :init_statuses,
    :init_types

  validates :name, :presence => true

  alias :project_users :users

  # Project owner
  belongs_to :user
  alias :owner :user

private

  def init_statuses
    self.ticket_statuses.create([{
      :name  => 'New',
      :color => 'gray',
      :close => false
    },{
      :name  => 'Resolved',
      :color => 'green',
      :close => false
    },{
      :name  => 'Closed',
      :color => 'red',
      :close => true
    }])
    self.default_status = self.ticket_statuses.where("name = 'New'").first
    self.save
  end

  def init_types
    self.ticket_types.create([{
      :name  => 'Feature',
      :color => 'green'
    },{
      :name  => 'Bug',
      :color => 'red'
    },{
      :name  => 'Chore',
      :color => 'orange'
    }])
  end

  def create_association_with_author
    self.owner.projects << self
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  load_and_authorize_resource

  respond_to :js

  def create
    create! do |format|
      format.js { render :text => project_tickets_path(@project) }
    end
  end

private

  def begin_of_association_chain
    current_user
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= semantic_form_for @project, :remote => true do |f|
  = f.inputs :name
  = f.buttons

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'
|
= link_to 'Ticket Statuses', project_ticket_statuses_path(@project)
|
= link_to 'Ticket Types', project_ticket_types_path(@project)
|
= link_to 'Delete Project', @project, :confirm => 'Are you sure?', :method => :delete

app/views/projects/index.html.haml
%h1 Listing projects
%table
  %tr
    %th Name
    %th
    %th
    %th
  - @projects.each do |project|
    %tr
      %td= link_to project.name, project_tickets_path(project)
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete
      %td= link_to 'Users of project', project_project_users_path(project)
%br/
= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
= render 'form'